
language: ruby
rvm:
- 2.5.1
script: "bundle exec jekyll build -V --trace"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  verbose: true
  on:
    branch: master
  target-branch: master
