# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: random parts
email:
description: > # this means to ignore newlines until "baseurl:"
  ©2019 random parts

# the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://random.parts"

#twitter_username:
github_username:  random-parts

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-versioned_files

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true

syntax_highlighter: rouge

show_dir_listing: false

excerpt_separator: <!--more-->

collections:
#  travel:
#    output: true
#    permalink: /:collection/:slug
  versioned_files:
    output: true
    versioned: true

versioned_file_options:
  files: _dyslexia/adhd-dyslexia.md
  formatting:
    diff_limit: true
    output: html
  frontmatter:
    sha: commit

defaults:
  -
    scope:
      type: travel
    values:
      layout: travel-single
  -
    scope:
      path: "dyslexia.md"
    values:
      permalink: /adhd-dyslexia/

array: []

sass:
  sass_dir: _sass
  style: compressed
